/*SG procedure
	- SGPanel: Generates a panel graph based upon the value of classsification variables. Can generate plots and layouts.
	- SGPLOT: Generates one or more plots which can be overlayed on one single set of axes. Histogram, Scatter, Line Plot
	- SGScatter: SGScatter- Generates a panel graph of scatter plots. Allow you to alter the appearence of plots.
	-SGrender: Used to generate graphical representation of templates. Generated by graph template language
	-SGdesign: Generages graph using sas datasets. Uses sdg file --> User defined application created by sas ods graphic
		 	   designer application
All of these belong to the ods graphics framework. 

Step1: Create SGPanel to create a panel of historgrams
	i. ODS Statements: Redirects destination to graphics. 
	Options - reset: resets all options to default; imagemap - specifies that you wish to generate datatips
	
	Panelby: Specifies one or more classification variables for the panel
	Histogram: Specifies that we want to create a histogram based on the horsepower
	Density: Creates a density curve that shows the distributional values of our data --> If the distribution is normal or not
	Can help in identifying a normal distribution

*/	

/*Step1*/
ods graphics /reset imagemap;

proc sgpanel data=sashelp.cars;
	title 'Horsepower distribution of cars';
	
	panelby Origin;
	histogram Horsepower;
	density Horsepower;
run;

ods graphics /reset;


proc means data = sashelp.cars;
	var horsepower;
run;	

ods _all_ close;
ods listing;